pub(crate) const CONFIG: AiConfig = AiConfig {
    directory: "ai",
    attachments_directory: "attachments",
    database_file_name: "chat.sqlite3",
    default_conversation_id: "default",
    chat_history_default_limit: 200,
    chat_history_max_limit: 1000,
    settings_file_name: "ai_settings.json",
    keyring_service: "dev.byteatatime.beam.ai",
    openrouter_keyring_username: "openrouter_api_key",
    openai_keyring_username: "openai_api_key",
    anthropic_keyring_username: "anthropic_api_key",
    gemini_keyring_username: "gemini_api_key",
    default_openrouter_model: "moonshotai/kimi-k2.5",
    default_openai_model: "gpt-5.2-2025-12-11",
    default_anthropic_model: "claude-sonnet-4-6",
    default_gemini_model: "gemini-3-flash-preview",
    default_openai_reasoning_effort: "medium",
    openai_context_window_tokens: 400_000,
    openai_max_output_tokens: 128_000,
    gemini_context_window_tokens: 1_000_000,
    gemini_max_output_tokens: 64_000,
    anthropic_context_window_tokens: 200_000,
    anthropic_max_output_tokens: 64_000,
    openrouter_context_window_tokens: 200_000,
    openrouter_max_output_tokens: 64_000,
    context_estimated_chars_per_token: 4,
    context_message_overhead_tokens: 24,
    context_input_headroom_tokens: 4_096,
    context_messages_limit: 400,
    context_keep_recent_messages: 24,
    context_min_messages_to_compact: 8,
    context_max_compaction_passes: 2,
    max_attachments: 8,
    max_attachment_base64_bytes: 25 * 1024 * 1024,
};

pub(crate) struct AiConfig {
    pub directory: &'static str,
    pub attachments_directory: &'static str,
    pub database_file_name: &'static str,
    pub default_conversation_id: &'static str,
    pub chat_history_default_limit: u32,
    pub chat_history_max_limit: u32,
    pub settings_file_name: &'static str,
    pub keyring_service: &'static str,
    pub openrouter_keyring_username: &'static str,
    pub openai_keyring_username: &'static str,
    pub anthropic_keyring_username: &'static str,
    pub gemini_keyring_username: &'static str,
    pub default_openrouter_model: &'static str,
    pub default_openai_model: &'static str,
    pub default_anthropic_model: &'static str,
    pub default_gemini_model: &'static str,
    pub default_openai_reasoning_effort: &'static str,
    pub openai_context_window_tokens: u64,
    pub openai_max_output_tokens: u64,
    pub gemini_context_window_tokens: u64,
    pub gemini_max_output_tokens: u64,
    pub anthropic_context_window_tokens: u64,
    pub anthropic_max_output_tokens: u64,
    pub openrouter_context_window_tokens: u64,
    pub openrouter_max_output_tokens: u64,
    pub context_estimated_chars_per_token: usize,
    pub context_message_overhead_tokens: u64,
    pub context_input_headroom_tokens: u64,
    pub context_messages_limit: u32,
    pub context_keep_recent_messages: u32,
    pub context_min_messages_to_compact: u32,
    pub context_max_compaction_passes: u32,
    pub max_attachments: usize,
    pub max_attachment_base64_bytes: usize,
}
