import type { CommandDescriptor, CommandScope } from "@/command-registry/types";

const SCOPE_NORMAL: CommandScope[] = ["normal"];
const SCOPE_NORMAL_COMPRESSED: CommandScope[] = ["normal", "compressed"];
const SCOPE_NORMAL_COMPRESSED_QUICKLINK: CommandScope[] = [
  "normal",
  "compressed",
  "quicklink-trigger",
];
const SCOPE_NORMAL_COMPRESSED_SYSTEM: CommandScope[] = [
  "normal",
  "compressed",
  "system-trigger",
];
const SCOPE_ALL: CommandScope[] = ["all"];

const SYSTEM_ACTION_DESCRIPTORS: CommandDescriptor[] = [
  {
    id: "system.shutdown",
    title: "shutdown",
    keywords: ["shutdown", "power off", "turn off", "shut down"],
    endText: "system",
    icon: "system",
    kind: "backend-action",
    scope: SCOPE_NORMAL_COMPRESSED_SYSTEM,
    requiresQuery: true,
    action: {
      type: "INVOKE_TAURI",
      payload: {
        command: "execute_system_action",
        args: { action: "shutdown" },
      },
    },
  },
  {
    id: "system.reboot",
    title: "reboot",
    keywords: ["reboot", "restart"],
    endText: "system",
    icon: "system",
    kind: "backend-action",
    scope: SCOPE_NORMAL_COMPRESSED_SYSTEM,
    requiresQuery: true,
    action: {
      type: "INVOKE_TAURI",
      payload: {
        command: "execute_system_action",
        args: { action: "reboot" },
      },
    },
  },
  {
    id: "system.logout",
    title: "logout",
    keywords: ["logout", "log out", "sign out"],
    endText: "system",
    icon: "system",
    kind: "backend-action",
    scope: SCOPE_NORMAL_COMPRESSED_SYSTEM,
    requiresQuery: true,
    action: {
      type: "INVOKE_TAURI",
      payload: {
        command: "execute_system_action",
        args: { action: "logout" },
      },
    },
  },
  {
    id: "system.sleep",
    title: "sleep",
    keywords: ["sleep", "suspend"],
    endText: "system",
    icon: "system",
    kind: "backend-action",
    scope: SCOPE_NORMAL_COMPRESSED_SYSTEM,
    requiresQuery: true,
    action: {
      type: "INVOKE_TAURI",
      payload: {
        command: "execute_system_action",
        args: { action: "sleep" },
      },
    },
  },
  {
    id: "system.hibernate",
    title: "hibernate",
    keywords: ["hibernate", "deep sleep"],
    endText: "system",
    icon: "system",
    kind: "backend-action",
    scope: SCOPE_NORMAL_COMPRESSED_SYSTEM,
    requiresQuery: true,
    action: {
      type: "INVOKE_TAURI",
      payload: {
        command: "execute_system_action",
        args: { action: "hibernate" },
      },
    },
  },
  {
    id: "system.awake",
    title: "keep awake",
    keywords: ["keep awake", "prevent sleep", "no sleep", "awake", "awake"],
    endText: "toggle",
    icon: "system",
    kind: "backend-action",
    scope: SCOPE_NORMAL_COMPRESSED_SYSTEM,
    requiresQuery: true,
    action: {
      type: "INVOKE_TAURI",
      payload: {
        command: "toggle_awake",
      },
    },
  },
];

export const STATIC_COMMANDS: CommandDescriptor[] = [
  {
    id: "settings.panel.open",
    title: "settings",
    keywords: ["settings", "style", "layout", "density", "glassy", "hotkeys", "shortcuts"],
    endText: "open",
    icon: "settings",
    kind: "panel",
    scope: SCOPE_NORMAL_COMPRESSED,
    action: {
      type: "OPEN_PANEL",
      payload: { panel: "settings" },
    },
  },
  {
    id: "todo.panel.open",
    title: "todo list",
    subtitle: "Tasks and subtasks",
    keywords: ["todo", "todos", "tasks", "task list", "checklist", "subtasks"],
    endText: "open",
    icon: "todo",
    kind: "panel",
    scope: SCOPE_NORMAL_COMPRESSED,
    action: {
      type: "OPEN_PANEL",
      payload: { panel: "todo" },
    },
  },
  {
    id: "clipboard.panel.open",
    title: "clipboard history",
    keywords: ["clipboard", "history"],
    endText: "open",
    icon: "clipboard",
    kind: "panel",
    scope: SCOPE_NORMAL,
    action: {
      type: "OPEN_PANEL",
      payload: { panel: "clipboard" },
    },
  },
  {
    id: "calculator.history.panel.open",
    title: "calculator history",
    keywords: ["calculator", "history"],
    endText: "open",
    icon: "calculator",
    kind: "panel",
    scope: SCOPE_NORMAL,
    action: {
      type: "OPEN_PANEL",
      payload: { panel: "calculator-history" },
    },
  },
  {
    id: "emoji.panel.open",
    title: "emoji picker",
    keywords: ["emoji", "picker", "emoticon", "smiley", "reaction", "kaomoji", "symbols"],
    endText: "open",
    icon: "emoji",
    kind: "panel",
    scope: SCOPE_NORMAL,
    action: {
      type: "OPEN_PANEL",
      payload: { panel: "emoji" },
    },
  },
  {
    id: "speed_test.panel.open",
    title: "network speed test",
    keywords: ["speed", "speed test", "internet speed", "network", "diagnostics"],
    endText: "network",
    icon: "speed-test",
    kind: "panel",
    scope: SCOPE_NORMAL_COMPRESSED_QUICKLINK,
    action: {
      type: "OPEN_PANEL",
      payload: { panel: "speed-test" },
    },
  },
  {
    id: "file_search.panel.open",
    title: "search files",
    subtitle: "File Search",
    keywords: ["files", "search files", "open file"],
    endText: "Command",
    icon: "files",
    kind: "panel",
    scope: SCOPE_NORMAL_COMPRESSED_QUICKLINK,
    requiresQuery: true,
    action: {
      type: "OPEN_PANEL",
      payload: { panel: "file-search" },
    },
  },
  {
    id: "dictionary.panel.open",
    title: "define word",
    subtitle: "Dictionary",
    keywords: ["dictionary", "word", "meaning", "define"],
    endText: "Command",
    icon: "dictionary",
    kind: "panel",
    scope: SCOPE_NORMAL_COMPRESSED,
    requiresQuery: true,
    action: {
      type: "OPEN_PANEL",
      payload: { panel: "dictionary" },
    },
  },
  {
    id: "translation.panel.open",
    title: "translate text",
    keywords: ["translate", "translation", "language", "convert text"],
    endText: "translate",
    icon: "translation",
    kind: "panel",
    scope: SCOPE_NORMAL_COMPRESSED_QUICKLINK,
    action: {
      type: "OPEN_PANEL",
      payload: { panel: "translation" },
    },
  },
  {
    id: "quicklinks.panel.create",
    title: "add quicklink",
    keywords: ["quicklink", "add quicklink", "create quicklink"],
    endText: "quicklink",
    icon: "quicklink-create",
    kind: "panel",
    scope: SCOPE_NORMAL_COMPRESSED,
    action: {
      type: "OPEN_PANEL",
      payload: { panel: "quicklinks", view: "create" },
    },
  },
  {
    id: "quicklinks.panel.manage",
    title: "manage quicklinks",
    keywords: ["quicklink", "manage quicklinks", "quicklink list"],
    endText: "quicklink",
    icon: "quicklink-manage",
    kind: "panel",
    scope: SCOPE_NORMAL_COMPRESSED,
    action: {
      type: "OPEN_PANEL",
      payload: { panel: "quicklinks", view: "manage" },
    },
  },
  {
    id: "extensions.panel.open",
    title: "manage extensions",
    subtitle: "Search, install, and uninstall extensions",
    keywords: [
      "extension",
      "extensions",
      "raycast",
      "store",
      "install extension",
      "uninstall extension",
      "ext",
    ],
    endText: "open",
    icon: "extension",
    kind: "panel",
    scope: SCOPE_NORMAL_COMPRESSED,
    action: {
      type: "OPEN_PANEL",
      payload: { panel: "extensions" },
    },
  },
  {
    id: "script_commands.panel.open",
    title: "script commands",
    subtitle: "Run and create local scripts",
    keywords: [
      "script",
      "scripts",
      "script commands",
      "shell",
      "bash",
      "automation",
      "terminal",
    ],
    endText: "open",
    icon: "terminal",
    kind: "panel",
    scope: SCOPE_NORMAL_COMPRESSED,
    action: {
      type: "OPEN_PANEL",
      payload: { panel: "script-commands" },
    },
  },
  {
    id: "hyprwhspr.panel.open",
    title: "hyprwhspr voice mode",
    subtitle: "Push-to-talk dictation controls",
    keywords: [
      "hyprwhspr",
      "voice mode",
      "whisper mode",
      "dictation mode",
      "speech to text",
      "whisper",
      "wispr",
    ],
    endText: "open",
    icon: "mic",
    kind: "panel",
    scope: SCOPE_NORMAL_COMPRESSED,
    action: {
      type: "OPEN_PANEL",
      payload: { panel: "hyprwhspr" },
    },
  },
  {
    id: "search.web.google",
    title: "search google",
    subtitle: "Browser",
    keywords: ["google", "web search", "search"],
    endText: "Quicklink",
    icon: "google",
    kind: "action",
    scope: SCOPE_NORMAL_COMPRESSED_QUICKLINK,
    requiresQuery: true,
    action: {
      type: "INVOKE_TAURI",
      payload: {
        command: "search_with_browser",
        args: { site: "google" },
      },
    },
  },
  {
    id: "search.web.duckduckgo",
    title: "search duckduckgo",
    subtitle: "Browser",
    keywords: ["duckduckgo", "ddg", "web search", "search"],
    endText: "Quicklink",
    icon: "duckduckgo",
    kind: "action",
    scope: SCOPE_NORMAL_COMPRESSED_QUICKLINK,
    requiresQuery: true,
    action: {
      type: "INVOKE_TAURI",
      payload: {
        command: "search_with_browser",
        args: { site: "duckduckgo" },
      },
    },
  },
  {
    id: "settings.layout.open",
    title: "ui density",
    keywords: ["ui density", "expand", "compress", "size", "layout"],
    endText: "size",
    icon: "layout",
    kind: "panel",
    scope: SCOPE_ALL,
    hidden: true,
    action: {
      type: "OPEN_PANEL",
      payload: { panel: "settings", view: "layout" },
    },
  },
  ...SYSTEM_ACTION_DESCRIPTORS,
];
