pub(crate) const CONFIG: GithubConfig = GithubConfig {
    authorize_url: "https://github.com/login/oauth/authorize",
    token_url: "https://github.com/login/oauth/access_token",
    user_url: "https://api.github.com/user",
    issues_url: "https://api.github.com/issues",
    search_issues_url: "https://api.github.com/search/issues",
    api_version: "2022-11-28",
    user_agent: "beam-desktop",
    default_scopes: &["read:user", "repo", "read:org", "notifications"],
    default_issues_filter: "assigned",
    default_issues_state: "open",
    default_issues_sort: "updated",
    default_issues_direction: "desc",
    default_issues_per_page: 20,
    max_issues_per_page: 100,
};

pub(crate) struct GithubConfig {
    pub authorize_url: &'static str,
    pub token_url: &'static str,
    pub user_url: &'static str,
    pub issues_url: &'static str,
    pub search_issues_url: &'static str,
    pub api_version: &'static str,
    pub user_agent: &'static str,
    pub default_scopes: &'static [&'static str],
    pub default_issues_filter: &'static str,
    pub default_issues_state: &'static str,
    pub default_issues_sort: &'static str,
    pub default_issues_direction: &'static str,
    pub default_issues_per_page: u8,
    pub max_issues_per_page: u8,
}
