import path from "node:path";
import { readFileSync, writeFileSync } from "node:fs";

import { ensureDir, fileSizeBytes, repoRoot } from "./utils";

type EmojibaseCompactItem = {
  unicode: string;
  label: string;
  hexcode: string;
  order?: number;
  group?: number;
  tags?: string[];
};

type GeneratedEmojiData = {
  emoji: string;
  label: string;
  tags: string[];
  searchText: string;
  group: number;
  order: number;
  hexcode: string;
};

const CATEGORY_ORDER = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] as const;
const CATEGORY_INDEX = new Map<number, number>(CATEGORY_ORDER.map((category, index) => [category, index]));

const sourcePath = path.join(repoRoot, "node_modules", "emojibase-data", "en", "compact.json");
const outputPath = path.join(
  repoRoot,
  "apps",
  "desktop",
  "src",
  "generated",
  "emoji-data.ts",
);
const outputDir = path.dirname(outputPath);

function normalizeText(value: string): string {
  return value.trim().toLowerCase().replace(/\s+/g, " ");
}

function normalizeTags(tags: readonly string[] | undefined, label: string): string[] {
  if (!tags || tags.length === 0) {
    return [];
  }

  const normalizedLabel = normalizeText(label);
  const seen = new Set<string>();
  const normalizedTags: string[] = [];

  for (const tag of tags) {
    const normalizedTag = normalizeText(tag);
    if (normalizedTag.length === 0 || normalizedTag === normalizedLabel || seen.has(normalizedTag)) {
      continue;
    }
    seen.add(normalizedTag);
    normalizedTags.push(normalizedTag);
  }

  return normalizedTags;
}

function sortEmojis(left: GeneratedEmojiData, right: GeneratedEmojiData): number {
  const leftCategoryIndex = CATEGORY_INDEX.get(left.group) ?? Number.MAX_SAFE_INTEGER;
  const rightCategoryIndex = CATEGORY_INDEX.get(right.group) ?? Number.MAX_SAFE_INTEGER;

  if (leftCategoryIndex !== rightCategoryIndex) {
    return leftCategoryIndex - rightCategoryIndex;
  }

  if (left.order !== right.order) {
    return left.order - right.order;
  }

  return left.hexcode.localeCompare(right.hexcode);
}

function toGeneratedEmojiData(items: readonly EmojibaseCompactItem[]): GeneratedEmojiData[] {
  return items
    .map((item) => {
      const label = normalizeText(item.label);
      const tags = normalizeTags(item.tags, label);

      return {
        emoji: item.unicode,
        label,
        tags,
        searchText: [label, ...tags].join(" "),
        group: item.group ?? 0,
        order: item.order ?? 0,
        hexcode: item.hexcode.toUpperCase(),
      } satisfies GeneratedEmojiData;
    })
    .sort(sortEmojis);
}

function buildSource(items: readonly GeneratedEmojiData[]): string {
  return [
    '// generated by "bun infra/scripts/generate-emoji-data.ts"',
    'import type { EmojiData } from "@/modules/emoji/types";',
    "",
    `export const EMOJI_DATA = ${JSON.stringify(items, null, 2)} satisfies readonly EmojiData[];`,
    "",
  ].join("\n");
}

function main() {
  const source = readFileSync(sourcePath, "utf8");
  const rawItems = JSON.parse(source) as EmojibaseCompactItem[];
  const generatedItems = toGeneratedEmojiData(rawItems);
  const output = buildSource(generatedItems);

  ensureDir(outputDir);
  writeFileSync(outputPath, output, "utf8");

  const outputBytes = fileSizeBytes(outputPath);
  console.log(`generated ${generatedItems.length} emojis -> ${path.relative(repoRoot, outputPath)} (${outputBytes} bytes)`);
}

main();
