pub(crate) const CONFIG: SpotifyConfig = SpotifyConfig {
    authorize_url: "https://accounts.spotify.com/authorize",
    token_url: "https://accounts.spotify.com/api/token",
    me_url: "https://api.spotify.com/v1/me",
    player_url: "https://api.spotify.com/v1/me/player",
    player_devices_url: "https://api.spotify.com/v1/me/player/devices",
    player_play_url: "https://api.spotify.com/v1/me/player/play",
    player_pause_url: "https://api.spotify.com/v1/me/player/pause",
    player_next_url: "https://api.spotify.com/v1/me/player/next",
    player_previous_url: "https://api.spotify.com/v1/me/player/previous",
    search_url: "https://api.spotify.com/v1/search",
    default_scopes: &[
        "user-read-private",
        "user-read-email",
        "user-read-playback-state",
        "user-modify-playback-state",
        "user-read-currently-playing",
    ],
    default_search_types: &["track", "artist", "album"],
    search_default_limit: 20,
    search_max_limit: 50,
};

pub(crate) struct SpotifyConfig {
    pub authorize_url: &'static str,
    pub token_url: &'static str,
    pub me_url: &'static str,
    pub player_url: &'static str,
    pub player_devices_url: &'static str,
    pub player_play_url: &'static str,
    pub player_pause_url: &'static str,
    pub player_next_url: &'static str,
    pub player_previous_url: &'static str,
    pub search_url: &'static str,
    pub default_scopes: &'static [&'static str],
    pub default_search_types: &'static [&'static str],
    pub search_default_limit: u8,
    pub search_max_limit: u8,
}
