pub(crate) const CONFIG: FileSearchConfig = FileSearchConfig {
    ignored_folders: &[
        "node_modules",
        "target",
        "dist",
        "build",
        ".build",
        "out",
        ".out",
        "coverage",
        ".coverage",
        ".nyc_output",
        "vendor",
        ".git",
        ".svn",
        ".hg",
        "__pycache__",
        ".venv",
        "venv",
        "env",
        ".env",
        ".pytest_cache",
        ".mypy_cache",
        ".ruff_cache",
        ".tox",
        ".nox",
        ".hypothesis",
        ".ipynb_checkpoints",
        ".gradle",
        ".idea",
        ".vscode",
        ".vs",
        "Debug",
        "Release",
        ".next",
        ".nuxt",
        ".svelte-kit",
        ".parcel-cache",
        ".turbo",
        ".yarn",
        ".pnpm-store",
        ".npm",
        ".bun",
        ".direnv",
        ".dart_tool",
        ".terraform",
        ".serverless",
        ".aws-sam",
        ".vercel",
        ".output",
        ".angular",
        ".history",
        ".Trash",
        "Trash",
        "tmp",
        "temp",
        ".sass-cache",
        "$RECYCLE.BIN",
        "System Volume Information",
        ".cache",
        ".cargo",
        ".rustup",
    ],
    ignored_files: &[
        ".DS_Store",
        "Thumbs.db",
        "desktop.ini",
        "Icon\r",
        ".localized",
        ".eslintcache",
        ".stylelintcache",
    ],
    cache_flush_debounce_ms: 2_000,
    watcher_debounce_secs: 1,
    default_results_per_page: 20,
    max_results_per_page: 100,
};

pub(crate) struct FileSearchConfig {
    pub ignored_folders: &'static [&'static str],
    pub ignored_files: &'static [&'static str],
    pub cache_flush_debounce_ms: u64,
    pub watcher_debounce_secs: usize,
    pub default_results_per_page: usize,
    pub max_results_per_page: usize,
}
